name: platformer-rl
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - pip
  - python=3.9
  - pytorch=2.0.1
  - stable-baselines3=1.4.0
  - pip:
    - numpy==1.23.2
    - pygame==2.1.2
    - ray[rllib]==2.0.0

